<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [1]:
import pandas as pd
import psycopg2

In [ ]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python

In [3]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [4]:
# текст запроса
query_3_1 = f'''SELECT count(*)
FROM vacancies
'''

In [5]:
# результат запроса
df = pd.read_sql_query(query_3_1 , connection)
df

/tmp/ipykernel_351982/619879664.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1 , connection)

   count
0  49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [6]:
# текст запроса
query_3_2 = f'''SELECT count(*)
FROM employers
'''

In [7]:
# результат запроса
df = pd.read_sql_query(query_3_2 , connection)
df

/tmp/ipykernel_351982/393902768.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_2 , connection)

   count
0  23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [8]:
# текст запроса
query_3_3 = f'''SELECT COUNT(DISTINCT id)
FROM areas;
'''

In [9]:
# результат запроса
df = pd.read_sql_query(query_3_3 , connection)
df

/tmp/ipykernel_351982/536905517.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_3 , connection)

   count
0   1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [10]:
# текст запроса
query_3_4 = f'''SELECT COUNT(DISTINCT id)
FROM industries;
'''

In [11]:
# результат запроса
df = pd.read_sql_query(query_3_4 , connection)
df

/tmp/ipykernel_351982/3642322098.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_4 , connection)

   count
0    294

***

In [ ]:
# выводы по предварительному анализу данных
# предварительный анализ данных показал, что в базе данных Вакансий содержится: "49197" вакансий, "23501" работадателей, "1362" регионов, "294" сферы деятельности.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [12]:
# текст запроса
query_4_1 = f'''SELECT a.name AS area, COUNT(v.id) AS cnt
FROM areas a
LEFT JOIN vacancies v ON a.id = v.area_id
GROUP BY a.id, a.name
ORDER BY cnt DESC
LIMIT 10;
'''

In [13]:
# результат запроса
df = pd.read_sql_query(query_4_1 , connection)
df

/tmp/ipykernel_351982/2502363374.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_1 , connection)

              area   cnt
0           Москва  5333
1  Санкт-Петербург  2851
2            Минск  2112
3      Новосибирск  2006
4           Алматы  1892
5     Екатеринбург  1698
6  Нижний Новгород  1670
7           Казань  1415
8        Краснодар  1301
9           Самара  1144

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [14]:
# текст запроса
query_4_2 = f'''SELECT COUNT(*) AS cnt
FROM vacancies
WHERE salary_from IS NOT NULL 
    OR salary_to IS NOT NULL;
'''

In [15]:
# результат запроса
df = pd.read_sql_query(query_4_2 , connection)
df

/tmp/ipykernel_351982/2246956196.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_2 , connection)

     cnt
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [16]:
# текст запроса
query_4_3 = f'''SELECT 
    ROUND(AVG(salary_from)) AS avg_salary_from,
    ROUND(AVG(salary_to)) AS avg_salary_to
FROM vacancies
WHERE salary_from IS NOT NULL 
    OR salary_to IS NOT NULL;
'''

In [17]:
# результат запроса
df = pd.read_sql_query(query_4_3 , connection)
df

/tmp/ipykernel_351982/3384291586.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_3 , connection)

   avg_salary_from  avg_salary_to
0          71065.0       110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [18]:
# текст запроса
query_4_4 = f'''SELECT 
    schedule,
    employment,
    COUNT(*) AS cnt
FROM vacancies
GROUP BY schedule, employment
ORDER BY cnt DESC;
'''

In [19]:
# результат запроса
df = pd.read_sql_query(query_4_4 , connection)
df

/tmp/ipykernel_351982/277711264.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_4 , connection)

            schedule           employment    cnt
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [20]:
# текст запроса
query_4_5 = f'''SELECT 
    experience,
    COUNT(*) AS cnt
FROM vacancies
WHERE schedule = 'Удаленная работа' 
  AND employment = 'Полная занятость'
GROUP BY experience
ORDER BY cnt ASC;
'''

In [21]:
# результат запроса
df = pd.read_sql_query(query_4_5 , connection)
df

/tmp/ipykernel_351982/1153066112.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_5 , connection)

           experience   cnt
0         Более 6 лет   218
1           Нет опыта   878
2       От 3 до 6 лет  2960
3  От 1 года до 3 лет  3746

***

In [ ]:
# выводы по детальному анализу вакансий
# При детальном выводе вакансий мы узнали следующее: Порядок лидеров вакансий "Москва, Санкт-Петербург, Минск, Новосибирск, Алматы", у "24073" количества вакансий заполнено одно из полей зарплатной вилки, нижняя граница зарплаты средняя "71065.0" верхняя средняя"110537.0", "Удалённая работа — Полная занятость" вторая по популярности типов вакансий, порядок вакансий по опыту "Более 6 лет — Нет опыта — От 3 до 6 лет — От 1 года до 3 лет"

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [22]:
# текст запроса
query_5_1 = f'''WITH ranked_employers AS (
    SELECT 
        e.name AS employer_name,
        COUNT(v.id) AS vacancy_count,
        DENSE_RANK() OVER (ORDER BY COUNT(v.id) DESC) AS rank_position
    FROM employers e
    LEFT JOIN vacancies v ON e.id = v.employer_id
    GROUP BY e.id, e.name
)
SELECT *
FROM ranked_employers
WHERE rank_position IN (1, 5)
ORDER BY rank_position;
'''

In [23]:
# результат запроса
df = pd.read_sql_query(query_5_1 , connection)
df

/tmp/ipykernel_351982/595224520.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_1 , connection)

   employer_name  vacancy_count  rank_position
0         Яндекс           1933              1
1  Газпром нефть            331              5

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [24]:
# текст запроса
query_5_2 = f'''SELECT 
    a.name AS region_name,
    COUNT(DISTINCT e.id) AS employers_count,
    COUNT(v.id) AS vacancies_count
FROM areas a
LEFT JOIN employers e ON e.area = a.id
LEFT JOIN vacancies v ON v.area_id = a.id
GROUP BY a.id, a.name
HAVING COUNT(v.id) = 0
ORDER BY employers_count DESC
LIMIT 1;
'''

In [25]:
# результат запроса
df = pd.read_sql_query(query_5_2 , connection)
df

/tmp/ipykernel_351982/3265235493.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_2 , connection)

  region_name  employers_count  vacancies_count
0      Россия              410                0

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [26]:
# текст запроса
query_5_3 = f'''SELECT 
    e.name AS employer_name,
    COUNT(DISTINCT v.area_id) AS regions_count
FROM employers e
LEFT JOIN vacancies v ON e.id = v.employer_id
GROUP BY e.id, e.name
ORDER BY regions_count DESC;
'''

In [27]:
# результат запроса
df = pd.read_sql_query(query_5_3 , connection)
df

/tmp/ipykernel_351982/571946965.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_3 , connection)

                employer_name  regions_count
0                      Яндекс            181
1                  Ростелеком            152
2                  Спецремонт            116
3      Поляков Денис Иванович             88
4                   ООО ЕФИН              71
...                       ...            ...
23496              Но Смокинг              0
23497        МАСТЕРСКАЯ CREED              0
23498           Dzing Finance              0
23499                    КОРС              0
23500             Наука-Связь              0

[23501 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [28]:
# текст запроса
query_5_4 = f'''SELECT COUNT(*) AS employers_without_industry
FROM employers e
WHERE NOT EXISTS (
    SELECT 1 
    FROM employers_industries ei 
    WHERE ei.employer_id = e.id
);
'''

In [29]:
# результат запроса
df = pd.read_sql_query(query_5_4 , connection)
df

/tmp/ipykernel_351982/4258316822.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_4 , connection)

   employers_without_industry
0                        8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [30]:
# текст запроса
query_5_5 = f'''WITH companies_with_industries AS (
    SELECT 
        e.id,
        e.name,
        COUNT(ei.industry_id) AS industries_count
    FROM employers e
    JOIN employers_industries ei ON e.id = ei.employer_id
    GROUP BY e.id, e.name
    HAVING COUNT(ei.industry_id) = 4
)
SELECT name AS company_name
FROM (
    SELECT 
        name,
        ROW_NUMBER() OVER (ORDER BY name ASC) AS rn
    FROM companies_with_industries
) ranked
WHERE rn = 3
'''

In [31]:
# результат запроса
df = pd.read_sql_query(query_5_5 , connection)
df

/tmp/ipykernel_351982/3525620180.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_5 , connection)

  company_name
0         2ГИС

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [32]:
# текст запроса
query_5_6 = f'''SELECT COUNT(*) AS employers_count
FROM employers e
WHERE EXISTS (
    SELECT 1
    FROM employers_industries ei
    JOIN industries i ON ei.industry_id = i.id
    WHERE ei.employer_id = e.id
      AND i.name = 'Разработка программного обеспечения'
)
'''

In [33]:
# результат запроса
df = pd.read_sql_query(query_5_6 , connection)
df

/tmp/ipykernel_351982/1002643217.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_6 , connection)

   employers_count
0             3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [34]:
import requests
from lxml import html

url = 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}

response = requests.get(url, headers=headers)
tree = html.fromstring(response.content)

# XPath к tbody таблицы
tbody = tree.xpath('/html/body/div[3]/div/div[3]/main/div[3]/div[3]/div[1]/section[2]/table/tbody')[0]

# Получаем все строки
rows = tbody.xpath('.//tr')

cities = []
for row in rows[1:]:  # пропускаем заголовок
    cells = row.xpath('.//td')
    if len(cells) >= 2:
        city = cells[1].xpath('.//a/text()')
        if city:
            city_name = city[0]
        else:
            city_name = cells[1].text_content().strip()
        cities.append(city_name)

# Выводим только города
cities_string = "', '".join(cities)
print("Города-миллионеры России:\n")
for city in cities:
    print(f"{city}")

Города-миллионеры России:

Москва
Санкт-Петербург
Новосибирск
Екатеринбург
Казань
Красноярск
Нижний Новгород
Челябинск
Уфа
Краснодар
Самара
Ростов-на-Дону
Омск
Воронеж
Пермь
Волгоград

In [35]:
# текст запроса
query_5_7 = f'''SELECT 
    COALESCE(a.name, 'Total') AS region_name,
    COUNT(v.id) AS vacancy_count
FROM vacancies v
JOIN areas a ON v.area_id = a.id
WHERE v.employer_id = (SELECT id FROM employers WHERE name = 'Яндекс')
  AND a.name IN (
    '{cities_string}'
  )
GROUP BY ROLLUP(a.name)
ORDER BY COALESCE(a.name, 'Total') = 'Total' DESC, vacancy_count DESC;
'''

In [36]:
# результат запроса
df = pd.read_sql_query(query_5_7 , connection)
df

/tmp/ipykernel_351982/4286935689.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_7 , connection)

        region_name  vacancy_count
0             Total            485
1            Москва             54
2   Санкт-Петербург             42
3      Екатеринбург             39
4   Нижний Новгород             36
5       Новосибирск             35
6           Воронеж             32
7         Краснодар             30
8            Самара             26
9               Уфа             26
10            Пермь             25
11   Ростов-на-Дону             25
12           Казань             25
13        Волгоград             24
14       Красноярск             23
15        Челябинск             22
16             Омск             21

***

In [ ]:
# выводы по анализу работодателей
# по результатам анализа выявили следующее: "Яндекс" на первом месте по количеству вакансий, "газпром-нефть" на пятом, количество регионов в которых он публикует вакансии "181", у "8419" количества работодателей не указана сфера деятельности, третья компания у которой указано четыре сферы деятельности это  "2ГИС", "3553" работодалетей в сфере разработки ПО, у "Яндекс" "485" опубликованных вакансий в городах миллионика.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [37]:
# текст запроса
query_6_1 = f'''SELECT COUNT(*) AS count
FROM vacancies
WHERE LOWER(name) LIKE '%data%' 
   OR LOWER(name) LIKE '%данн%';
'''

In [38]:
# результат запроса
df = pd.read_sql_query(query_6_1 , connection)
df

/tmp/ipykernel_351982/1247664232.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_1 , connection)

   count
0   1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [39]:
# текст запроса
query_6_2 = f'''SELECT COUNT(*) AS junior_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%ml%'      -- ML (позже исключим HTML)
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
)
AND (
    LOWER(name) LIKE '%junior%'
    OR experience = 'Нет опыта'
    OR employment = 'Стажировка'
)
AND NOT (LOWER(name) LIKE '%ml%' AND LOWER(name) LIKE '%html%');
'''

In [40]:
# результат запроса
df = pd.read_sql_query(query_6_2 , connection)
df

/tmp/ipykernel_351982/1887057144.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_2 , connection)

   junior_count
0            51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [41]:
# текст запроса
query_6_3 = f'''SELECT COUNT(*) AS ds_vacancies_with_sql_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%ml%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
)
AND NOT (LOWER(name) LIKE '%ml%' AND LOWER(name) LIKE '%html%')
AND (
    LOWER(key_skills) LIKE '%sql%' 
    OR LOWER(key_skills) LIKE '%postgres%'
);
'''

In [42]:
# результат запроса
df = pd.read_sql_query(query_6_3 , connection)
df

/tmp/ipykernel_351982/2267706848.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_3 , connection)

   ds_vacancies_with_sql_count
0                          229

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [43]:
# текст запроса
query_6_4 = f'''SELECT COUNT(*) AS ds_vacancies_with_python_count
FROM vacancies
WHERE (
    -- Условия для дата-сайентиста
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%ml%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
)
AND NOT (LOWER(name) LIKE '%ml%' AND LOWER(name) LIKE '%html%')
AND LOWER(key_skills) LIKE '%python%';
'''

In [44]:
# результат запроса
df = pd.read_sql_query(query_6_4 , connection)
df

/tmp/ipykernel_351982/492214577.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_4 , connection)

   ds_vacancies_with_python_count
0                             357

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [45]:
# текст запроса
query_6_5 = f'''SELECT 
    AVG(1 + LENGTH(key_skills) - LENGTH(REPLACE(key_skills, CHR(9), ''))) AS avg_skills_count
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR (LOWER(name) LIKE '%ml%' AND LOWER(name) NOT LIKE '%html%')
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
)
AND key_skills IS NOT NULL
AND key_skills != '';
'''

In [46]:
# результат запроса
df = pd.read_sql_query(query_6_5 , connection)
df

/tmp/ipykernel_351982/4174279570.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_5 , connection)

   avg_skills_count
0          6.546778

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [47]:
# текст запроса
query_6_6 = f'''SELECT 
    experience,
    ROUND(AVG(COALESCE((salary_from + salary_to) / 2.0, salary_from, salary_to))) AS avg_salary
FROM vacancies
WHERE (
    LOWER(name) LIKE '%data scientist%'
    OR LOWER(name) LIKE '%data science%'
    OR LOWER(name) LIKE '%исследователь данных%'
    OR LOWER(name) LIKE '%ml%'
    OR LOWER(name) LIKE '%machine learning%'
    OR LOWER(name) LIKE '%машинн%обучен%'
)
AND NOT (LOWER(name) LIKE '%ml%' AND LOWER(name) LIKE '%html%')
AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
GROUP BY experience;
'''

In [48]:
# результат запроса
df = pd.read_sql_query(query_6_6 , connection)
df

/tmp/ipykernel_351982/3698363061.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_6 , connection)

           experience  avg_salary
0         Более 6 лет    157933.0
1           Нет опыта     74643.0
2  От 1 года до 3 лет    144233.0
3       От 3 до 6 лет    256454.0

***

In [ ]:
# выводы по предметному анализу
# По результатам предметного анализа имеем "1771" вакансию связаннаю с данными в заголовке, "51" вакансию для начинающей позиции в дата-сайентиста, "229" вакансий дя ДС с ключевым навыком SQL или postgres, "357" вакансий для ДС с ключивым навыком Python, '6.41" в среднем необходимо навыков для данной професии, "256450" можно рассчитывать зарплату при стаже от 3 до 6 лет.

# Общий вывод по проекту

In [ ]:
# подведем итог исследования, обобщите выводы
# в процессе иследования мы выяснили: количество вакансий, тип работодателей, деление вакансий и работодателей по регионам, и провели исследования для вакансий типа дата-сайентиста.
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования
# можно продолжить дальнейшие иследования, например определить набор ключевых навыков для ДС выразив их через количестов всех навыков в данных вакансиях отфильтрованных по названию какого либо ключевого навыка.